//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karambolo.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Karambolo.Common.Properties.Resources", typeof(Resources).Assembly());
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination array was not long enough. Check arrayIndex and length, and the array&apos;s lower bounds..
        /// </summary>
        internal static string ArrayNotLongEnough {
            get {
                return ResourceManager.GetString("ArrayNotLongEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity must be non-negative..
        /// </summary>
        internal static string CapacityOutOfRange {
            get {
                return ResourceManager.GetString("CapacityOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change collection during a CollectionChanged event..
        /// </summary>
        internal static string ChangeDuringCollectionChangedEventNotSupported {
            get {
                return ResourceManager.GetString("ChangeDuringCollectionChangedEventNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serializing delegates targeting an object instance is not supported..
        /// </summary>
        internal static string DelegateSerializationNotSupported {
            get {
                return ResourceManager.GetString("DelegateSerializationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error handling cannot be set in the current state of object..
        /// </summary>
        internal static string ErrorHandlingCannotSet {
            get {
                return ResourceManager.GetString("ErrorHandlingCannotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies of money values must match..
        /// </summary>
        internal static string IncompatibleCurrencies {
            get {
                return ResourceManager.GetString("IncompatibleCurrencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index must be non-negative and less than the size of the collection..
        /// </summary>
        internal static string IndexOutOfRange {
            get {
                return ResourceManager.GetString("IndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid array type..
        /// </summary>
        internal static string InvalidArrayType {
            get {
                return ResourceManager.GetString("InvalidArrayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal state of object is invalid..
        /// </summary>
        internal static string InvalidInternalState {
            get {
                return ResourceManager.GetString("InvalidInternalState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key must be of type {0}..
        /// </summary>
        internal static string InvalidKeyType {
            get {
                return ResourceManager.GetString("InvalidKeyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid public key token. Size must be {0} bytes..
        /// </summary>
        internal static string InvalidPublicKeyToken {
            get {
                return ResourceManager.GetString("InvalidPublicKeyToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be of type {0}..
        /// </summary>
        internal static string InvalidValueType {
            get {
                return ResourceManager.GetString("InvalidValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of items to be replaced and items to replace with must be equal..
        /// </summary>
        internal static string ItemsToReplacedCountMismatch {
            get {
                return ResourceManager.GetString("ItemsToReplacedCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item to be moved is not present in the collection..
        /// </summary>
        internal static string ItemToMovedNotFound {
            get {
                return ResourceManager.GetString("ItemToMovedNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item to replace is already present in the collection..
        /// </summary>
        internal static string ItemToReplaceCannotAdded {
            get {
                return ResourceManager.GetString("ItemToReplaceCannotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item to be replaced cannot be removed or is not present in the collection..
        /// </summary>
        internal static string ItemToReplacedCannotRemoved {
            get {
                return ResourceManager.GetString("ItemToReplacedCannotRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-dimensional arrays are not supported..
        /// </summary>
        internal static string MultiDimArrayNotSupported {
            get {
                return ResourceManager.GetString("MultiDimArrayNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrays with non-zero lower bounds are not supported..
        /// </summary>
        internal static string NonZeroLowerBoundArrayNotSupported {
            get {
                return ResourceManager.GetString("NonZeroLowerBoundArrayNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression is not a field or property access expression..
        /// </summary>
        internal static string NotFieldOrPropertyExpression {
            get {
                return ResourceManager.GetString("NotFieldOrPropertyExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is not an open generic interface..
        /// </summary>
        internal static string NotGenericInterfaceType {
            get {
                return ResourceManager.GetString("NotGenericInterfaceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is not an interface..
        /// </summary>
        internal static string NotInterfaceType {
            get {
                return ResourceManager.GetString("NotInterfaceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel reset sections are not supported..
        /// </summary>
        internal static string ParallelResetSectionsNotSupported {
            get {
                return ResourceManager.GetString("ParallelResetSectionsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Populating destination object is failed because the existing value is not compatible with the source object. See exception data for details..
        /// </summary>
        internal static string PopulatingObjectFailed {
            get {
                return ResourceManager.GetString("PopulatingObjectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} cannot be null..
        /// </summary>
        internal static string PropertyCannotBeNull {
            get {
                return ResourceManager.GetString("PropertyCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified range exceeds the size of the collection..
        /// </summary>
        internal static string RangeExceedsCollectionSize {
            get {
                return ResourceManager.GetString("RangeExceedsCollectionSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object must be of type {0}..
        /// </summary>
        internal static string UnexpectedObjectType {
            get {
                return ResourceManager.GetString("UnexpectedObjectType", resourceCulture);
            }
        }
    }
}
